#!/bin/sh
set -e
NAME=SuSEfirewall2
VERSION=3.6
revs=`git rev-list master|wc -l`
# there are two empty commits in svn were not converted to git
# commits so increase revs by two
let revs=revs+2
vers="${VERSION:+${VERSION}.}$revs"
pfx="$NAME-$vers"
fn="$pfx".tar.bz2
git archive --prefix="$pfx"/ HEAD | bzip2 > $fn
echo "version $vers -> $fn"
