#! /bin/sh
# Copyright (c) 2000-2002 SuSE GmbH Nuernberg, Germany.
#
# Author: Marc Heuse <marc@suse.de>
#
# /etc/init.d/SuSEfirewall2_setup
#
### BEGIN INIT INFO
# Provides: SuSEfirewall2_setup
# Required-Start: SuSEfirewall2_init $network $local_fs
# Should-Start:   $ALL
# Required-Stop:  $local_fs
# Should-Stop:    $null
# Default-Start:  3 4 5
# Default-Stop:   0 1 2 6
# Short-Description: SuSEfirewall2 phase 2
# Description: SuSEfirewall2_setup does some basic setup and is the
#	phase 2 of 2 of the SuSEfirewall initialization.
### END INIT INFO
# X-SuSE-Dep-Only

SUSEFWALL="/sbin/SuSEfirewall2"

test -x $SUSEFWALL || exit 5

bootlinkisset()
{
	local l
	l=`/sbin/runlevel | (read A B && echo $A)`
	test -e /etc/init.d/rc$l.d/S??SuSEfirewall2_setup
}

. /etc/rc.status
rc_reset

case "$1" in
    start)
	echo -n "Starting Firewall Initialization "
	echo -n '(phase 2 of 2) '
	$SUSEFWALL -q --bootunlock start
	rc_status -v
	;;
    stop)
	echo -n "Shutting down the Firewall "
	if [ -z "$REDIRECT" ]; then
		$SUSEFWALL -q stop
		rc_status -v
	else
		rc_status -s
	fi
	;;
    restart|force-reload)
	$0 start
	;;
    try-restart|reload)
	if ($0 status) >/dev/null 2>&1; then
	    $0 start
	else
	    rc_reset
	fi
	;;
    long-status)
	echo "Checking the status of SuSEfirewall2 "
	if ! $SUSEFWALL status; then
		rc_failed 3
	fi
	;;
    status)
	echo -n "Checking the status of SuSEfirewall2 "
	iptables -nL reject_func >/dev/null 2>&1 || rc_failed 3
	rc_status -v
	;;
    *)
	echo "Usage: $0 {start|stop|status|restart|reload|force-reload}"
	exit 1
	;;
esac

# Set exit status
rc_exit
