#!/bin/sh
set -e
NAME=SuSEfirewall2
VERSION=3.6
revs=`git rev-list HEAD|wc -l`
# there are two empty commits in svn were not converted to git
# commits so increase revs by two
let revs=revs+2
vers="${VERSION:+${VERSION}.}$revs"
pfx="$NAME-$vers"
fn="$pfx".tar.bz2
if ! git config --get tar.umask >/dev/null 2>&1 ; then
       git config --add tar.umask 022
fi
git archive --prefix="$pfx"/ HEAD | bzip2 > $fn
echo "VERSION=$vers"
echo "FILENAME=$fn"
